### ISSUE TITLE
Executing batch with `--local-executor` reports an error in CLI

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#305]
Steps to reproduce:
- `git clone https://github.com/neuro-inc/neuro-flow-examples && cd neuro-flow-examples`
- `neuro-flow bake multi-depth --local-executor`

Observe error message:
```
Exception ignored in: <function BaseEventLoop.__del__ at 0x7ffa1966d290>
Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/asyncio/base_events.py", line 628, in __del__
    self.close()
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/asyncio/unix_events.py", line 55, in close
    super().close()
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/asyncio/selector_events.py", line 91, in close
    self._close_self_pipe()
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/asyncio/selector_events.py", line 98, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/asyncio/selector_events.py", line 271, in _remove_reader
    key = self._selector.get_key(fd)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/selectors.py", line 190, in get_key
    return mapping[fileobj]
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/selectors.py", line 71, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.7/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

Yet, this error is ignored, and bake proceeds without problems.

Expected behavior: no error message appears with the local-executor. It is often used for batch debugging.

Versions:
```
neuro-cli                    21.2.19
neuro-extras                 20.12.16
neuro-flow                   21.2.16
neuro-sdk                    21.2.19
```

**Comment by romasku** [comment]
I'm unable to reproduce it with the latest version. Does this still happen ofter for you?

**Comment by YevheniiSemendiak** [comment]
Indeed, with the latest versions, all is OK. Thx!
