### ISSUE TITLE
Windows stderr traceback: RuntimeError('Event loop is closed')

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/neuro-flow#331]
```
tests/e2e/test_live.py::test_neuro_flow_ps                ╷         ╷        ╷       
  JOB          │ STATUS  │ RAW ID │ WHEN  
╶──────────────┼─────────┼────────┼──────╴
  filebrowser  │ unknown │ N/A    │ N/A   
  jupyter      │ unknown │ N/A    │ N/A   
  multitrain   │ unknown │ N/A    │ N/A   
  remote_debug │ unknown │ N/A    │ N/A   
  tensorboard  │ unknown │ N/A    │ N/A   
  train        │ unknown │ N/A    │ N/A   
               ╵         ╵        ╵       
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000011081464D38>
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\asyncio\proactor_events.py", line 86, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\asyncio\base_events.py", line 691, in call_soon
    self._check_closed()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\asyncio\base_events.py", line 479, in _check_closed
Error:     raise RuntimeError('Event loop is closed')
```

**Comment by YevheniiSemendiak** [comment]
The problem is actual again, see our cookie-cutter template test runs in https://github.com/neuro-inc/cookiecutter-neuro-project/pull/497:
1. https://github.com/neuro-inc/cookiecutter-neuro-project/runs/3372609890?check_suite_focus=true
2. https://github.com/neuro-inc/cookiecutter-neuro-project/actions/runs/1147314671

The problem is flaky, happens in all tested Python versions (3.6, 3.7, 3.8, 3.9) on Windows OS.
I also have a Windows-OS machine at home and could perform some tests if needed.
cc @romasku
