### ISSUE TITLE
Inspection crashes in analysis of cached subgraph

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#376]
Performing `neuro-flow inspect pipeline_2021-04-15T15:58:01+00:00_cf89f2` (Synthesis PCA-pipeline project in synthesis-aws cluster) causes neuro-flow to crash.
It crashes when reaches a cached task of subgraph, `get_face_assets.build_image`:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/32543098/116112274-15868080-a6c0-11eb-828c-daeb223caa3b.png">

(those tuples of IDs are printed out of [here](https://github.com/neuro-inc/neuro-flow/blob/master/neuro_flow/batch_runner.py#L461))

<details>
<summary> traceback </summary>

ERROR: <TaskStatus.CACHED: 'cached'>
Traceback (most recent call last):
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_flow/cli/main.py", line 184, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_flow/cli/utils.py", line 21, in wrapper
    return runner.run(callback(*args, **kwargs))
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_cli/asyncio_utils.py", line 53, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_flow/cli/batch.py", line 180, in inspect
    await runner.inspect(
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_flow/batch_runner.py", line 425, in inspect
    await self._subgraph(dot, graphs, (), {}, statuses, finished)
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_flow/batch_runner.py", line 474, in _subgraph
    await self._subgraph(
  File "/Users/ysem/opt/anaconda3/envs/neuro/lib/python3.9/site-packages/neuro_flow/batch_runner.py", line 462, in _subgraph
    color = GRAPH_COLORS[status]
KeyError: <TaskStatus.CACHED: 'cached'>

</details>

**Comment by YevheniiSemendiak** [comment]
@romasku, is there any work-around I could use until NF release? since currently, I cannot check statuses of bakes in CLI

**Comment by romasku** [comment]
Sorry, I am not aware of any workarounds. You can patch your local client manually, but it's not a good solution at all, I know.
