### ISSUE TITLE
GitHub verification via SSH error in the MacOS environment

### ISSUE THREAD

**Issue by dmitrynikolayev** [neuro-inc/neuro-flow#511]
I've encountered with a trouble on my MacOS machine concerned with GitHub SSL-verification triggered by gh-actions in live.yml.
I concider two approaches to solve it
1. We could disable SSL-verification by setting the flag in the environment GIT_SSL_NO_VERIFY=true or running the corresponding command
   $ git config http.sslVerify "false"
2. We could profide a certificate pem-file in ~/.gitconfig in the property sslCAInfo
But I could not perform this approaches in the environment where the github-actions are triggered.
If I delete all gh-actions from the live.yml everything works perfect.
Also I've tried to edit ~/.neuro/live.yml, ./.neuro/live.yml (default:env, bash) files providing the desired
state variables, id didn't help.
```
ERROR: Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]
Traceback (most recent call last):
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/cli/main.py", line 192, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/cli/utils.py", line 40, in wrapper
    return runner.run(callback(*args, **kwargs))
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_cli/asyncio_utils.py", line 55, in run
    return self._loop.run_until_complete(main_task)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/cli/live.py", line 77, in run
    await runner.run(
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/live_runner.py", line 438, in run
    job_meta = await self.flow.get_meta(job_id)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/context.py", line 1198, in get_meta
    action_ast = await self._get_action_ast(job_ast)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/context.py", line 1185, in _get_action_ast
    action_ast = await self._cl.fetch_action(action_name)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/config_loader.py", line 135, in fetch_action
    self.__action_cache[action_name] = await self._fetch_action(action_name)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/config_loader.py", line 130, in _fetch_action
    async with self.action_stream(action_name) as stream:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/config_loader.py", line 249, in action_stream
    async with self._tarball_from_github(repo, version) as tarball:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/neuro_flow/config_loader.py", line 277, in _tarball_from_github
    async with self._github_session.get(
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/dmitrynvm/Documents/Work/_tst/web/lib/python3.9/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')]
```

**Comment by romasku** [comment]
The `neuro-flow` tool does not use `git` tools to fetch actions from GitHub. So changing anything in git configuration cannot solve this issue.
To fetch action's config file, `neuro-flow` just requests `GET https://api.github.com/repos/{repo}/tarball/{version}"` using `aiohttp` basic functiolitty. Looks like your system cannot verify `api.github.com`'s certificate, which is quite strange. Does simple curl-ing works properly?
```
curl -L https://api.github.com/repos/neuro-inc/neuro-flow-test-action/tarball/v0.2
```

**Comment by dmitrynikolayev** [comment]
My git-client works perfectly fine, all SSL-certificates are generated and configured.
I've manage to solve this issue. The reason was that Python interpreter was not installed properly well.
In MacOS environment Python interpreter includes its own private copy of OpenSSL 1.1.1 (which is not compatible with the MacOS one), and we need to install a curated bundle of default root certificates from the third-party certifi package to make it possible to use SSL without limitations in Python applications. After installation you need manually run "Install Certificates.command” from MacOS Python installation package  to configure the SSL certificates needed by Python concerned with  certifi package according to the manual
https://flaviocopes.com/python-installation-macos/
Thank you for the reply, your comment helped me to debug and understand the internal processes of how the neuro apps affect github repos!

**Comment by romasku** [comment]
Got it, thank you for the explanation
