### ISSUE TITLE
No `volumes` field validation in batch mode

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#676]
Live description (the same problem appears in batch mode):
```yaml
kind: live

volumes:
  remote_dataset:
    remote: storage:${{ flow.project_id }}/dataset
    mount: /dataset

jobs:

  test:
    image: ubuntu
    volumes: ${{ volumes.remote_dataset.ref_ro }}
    cmd: df -h
```

<details>
<summary> traceback </summary>

```
nf run test
ERROR: while parsing a block mapping
  in "/Users/ysem/work/projects/neuro/ml/ml-recipe-bone-age/.neuro/live.yaml", line 24, column 3
expected <block end>, but found '<block mapping start>'
  in "/Users/ysem/work/projects/neuro/ml/ml-recipe-bone-age/.neuro/live.yaml", line 228, column 5
Traceback (most recent call last):
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/cli/main.py", line 193, in main
    cli.main(args=args, standalone_mode=False)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/cli/utils.py", line 40, in wrapper
    return runner.run(callback(*args, **kwargs))
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_cli/asyncio_utils.py", line 55, in run
    return self._loop.run_until_complete(main_task)
  File "/Users/ysem/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/cli/live.py", line 80, in run
    runner = await stack.enter_async_context(
  File "/Users/ysem/miniconda3/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/live_runner.py", line 102, in __aenter__
    await self.init_flow()
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/live_runner.py", line 88, in init_flow
    self._flow = await RunningLiveFlow.create(self._config_loader)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/context.py", line 1518, in create
    ast_flow = await config_loader.fetch_flow(config_name)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/config_loader.py", line 157, in fetch_flow
    self.__flow_cache[name] = await self._fetch_flow(name)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/config_loader.py", line 153, in _fetch_flow
    return parse_live_stream(stream)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/neuro_flow/parser.py", line 1037, in parse_live_stream
    ret = loader.get_single_data()
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/ysem/.local/pipx/venvs/neuro-flow/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/Users/ysem/work/projects/neuro/ml/ml-recipe-bone-age/.neuro/live.yaml", line 24, column 3
expected <block end>, but found '<block mapping start>'
  in "/Users/ysem/work/projects/neuro/ml/ml-recipe-bone-age/.neuro/live.yaml", line 228, column 5
(bones) {21-11-19 11:46}ysem@ysem-macpro:~/work/projects/neuro/ml/ml-recipe-bone-age@ys/batch_mode✗✗|
```

</details>

Maybe we could add some sort of JSON/YAML schema for validation?
Having it, we (MLOps team) could build some Neuro-Flow YAML config constructor for VSCode / PyCharm IDEs.

**Comment by asvetlov** [comment]
The error explicitly points to the problematic position in YAML.
I consider it as *validation*.

If you are requesting for hiding traceback by default by showing the error text only -- I agree, it should be a nice addition.

If you want to support external YAML schema -- maybe it is a good idea. Please feel free to provide it, no code changes are required.

**Comment by YevheniiSemendiak** [comment]
> If you are requesting for hiding traceback by default by showing the error text only -- I agree, it should be a nice addition.

yes, that would be good.

> If you want to support external YAML schema -- maybe it is a good idea. Please feel free to provide it, no code changes are required.

I was thinking of generating it from the NF's AST. Or it will be overkill and it would be easier to simply write it and update manually?

**Comment by asvetlov** [comment]
I don't know. 
AST is not a 1-1 mapping from YAML to parsed structures.
The parser sometimes does small tricks and corrections.
For example, take a look at `parser.py:parse_matrix`.

**Comment by YevheniiSemendiak** [comment]
Yeah, that's tricky..
Ok, let's only hide the traceback by default and show error text only in the context of this issue.
