### ISSUE TITLE
Suppress finalization error on Windows

### ISSUE THREAD

**Issue by asvetlov** [neuro-inc/neuro-flow#700]
```
Evgeniya  8:53 PM
(synth) C:\Users\79218\git\synth\landmarks-detection>neuro-flow run train
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002AD93233790>
Traceback (most recent call last):
  File "C:\Users\79218\anaconda3\envs\synth\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\79218\anaconda3\envs\synth\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\79218\anaconda3\envs\synth\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\79218\anaconda3\envs\synth\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by YevheniiSemendiak** [comment]
duplicate https://github.com/neuro-inc/neuro-flow/issues/331 ?

**Comment by asvetlov** [comment]
Yes, thanks!
